config/routes.rb
Brighter::Application.routes.draw do

  root :to => 'contents#index'

  devise_for :users
  
  resources :users do
    resources :comments
  end
  resources :comments

  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  resources :folders, only: [:create, :update, :destroy]
  resources :contents, only: [:index, :edit, :new, :create, :destroy, :update] do
    get 'publish'
    resources :content_layouts, only: [:show, :new, :create, :destroy, :update, :edit]
  end
  post "content_layouts/publish" => "content_layouts#publish"
  resources :authentications, only: [:new, :create, :destroy, :index]
  resources :layouts, only: [:index, :new, :create, :destroy, :update, :edit]

  post "endpoints/register_social_app" => "endpoints#register_social_app"
  resources :endpoints, only: [:index, :new, :create, :destroy, :update, :edit]
  resources :ftp_endpoints, :controller => "endpoints", :type => "FtpEndpoint"
  resources :sftp_endpoints, :controller => "endpoints", :type => "SftpEndpoint"
  resources :html_layouts, :controller => "layouts", :type => "HtmlLayout"


  resources :facebook_endpoints,
            controller: 'endpoints',
            type: 'FacebookEndpoint',
            only: [:index, :new, :create, :destroy, :update, :edit]
  resources :twitter_endpoints,
            controller: 'endpoints',
            type: 'TwitterEndpoint',
            only: [:index, :new, :create, :destroy, :update, :edit]

  namespace :admin do
    resources :users do
      get 'lookup'
      put 'update_user'
      post 'update_user'
      post 'remove_user'
    end
  end
  resources :images

  match '/auth/:provider/callback' => 'authentications#create'
end

app/models/content_layout.rb
class ContentLayout < ActiveRecord::Base
  attr_accessible :name,
                  :data,
                  :layout,
                  :content,
                  :layout_id,
                  :content_id,
                  :source,
                  :content_layout_endpoints_attributes,
                  :published
  belongs_to :content
  belongs_to :layout

  has_many :endpoints, through: :content_layout_endpoint
  has_many :content_layout_endpoints
  has_many :comments, :as => :commentable

  has_many :images

  serialize :data, JSON

  validates :name, presence: true
  validates :layout_id, presence: true
  validates :content_id, presence: true

  accepts_nested_attributes_for :content_layout_endpoints, :allow_destroy => true


  def source=(src)
    if src && src.kind_of?(Hash)
      src.each do |tag, img|
        images.build(:source => img, :content_tag_name => tag.dup)
      end
    end
  end

  before_save :check_data, :make_image_tags

  has_paper_trail

  def check_data
    if data_changed?
      self.published = false
      return true
    end
  end

  def make_image_tags
    images.each do |img|
      if !data.has_key?(img.content_tag_name)
        data[img.content_tag_name] = "<img src='" + img.source.original_filename + "' />"
      end
    end
  end

  def publish path=nil, filename=nil
    content_layout_endpoints.each do |p|
      case p.endpoint.type
      when "FacebookEndpoint", "TwitterEndpoint"
        data = self.data
      else
        data = { path: (!path.blank?) ? path : self.content.path,
                 filename: (!filename.blank?) ? filename : self.name, 
                 data: layout.combine(self.data),
                 image_ids: image_ids }
      end
      p.endpoint.publish(data)
    end
    update_attributes(published:true)
  end

  def publishable?
    return content_layout_endpoints.count > 0
  end
  
end

app/controllers/content_layouts_controller.rb
class ContentLayoutsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_content, except: :publish
  before_filter :load_content_layout, :only => [:show, :edit, :update]
  before_filter :collect_endpoints, only: [:new, :edit, :create]
  before_filter :collect_layouts, only: [:new, :edit, :create]


  def create
    @content = Content.find(params[:content_id])
    @content_layout = @content.content_layouts.build(params[:content_layout])
    if @content.save
      redirect_to edit_content_content_layout_path(@content, @content_layout)
    else
      render 'new'
    end
  end

  def new
    @content_layout = ContentLayout.new
  end

  def edit
    @fields = @content_layout.layout.get_fields
    @data = @content_layout.data || {}
  end

  def show
    layout = @content_layout.layout.content
    data = @content_layout.data
    ret = layout.dup
    layout.scan(/<content type=\"text\">([\w|\s]*?)<\/content>/) do |x|
      if x
        ret.gsub!('<content type="text">' + x.first + '</content>', data[x.first] || "" )
      end
    end
    layout.scan(/<content type=\"image\">([\w|\s]*?)<\/content>/) do |x|
      if x
        ret.gsub!('<content type="image">' + x.first + '</content>', @content_layout.images ? '<img src="' + @content_layout.images.select {|img| img.content_tag_name == x.first}[0].source.url + '" />' : "" )
      end
    end
    return render :text => ret
  end

  def update
    if @content_layout.update_attributes(params[:content_layout])
      flash[:success] = "#{undo_link}"
      redirect_to edit_content_content_layout_path(@content_layout.content, @content_layout)
    else
      @fields = @content_layout.layout.get_fields
      @data = @content_layout.data || {}


      params[:content_layout].delete(:content_layout_endpoints_attributes)
      params[:content_layout].delete(:data)

      render 'edit'
    end
  end

  def destroy
    ContentLayout.find(params["id"]).destroy
    redirect_to edit_content_path(@content)
  end

  def view_content_layout
    @content_content_layout = ContentLayout.find(params[:id])

    @content_layout_fields = {}

    data = @content_content_layout.data
    @content_layout.layout.layout.scan(/<content>([\w|\s]*?)<\/content>/) do |x|
      @content_layout_fields[x.first.strip] = data[x.first.strip]
    end
  end

  def publish
    cl = ContentLayout.find(params[:id])

    if cl.publish(params[:path], params[:filename])
      flash[:success] = "Content Layout published."
    else
      flash[:error] = "Content Layout could not be published."
    end

    redirect_to contents_path
  end

private

  def undo_link
    view_context.link_to("undo", revert_version_path(@content_layout.versions.scoped.last), :method => :post)
  end

  def load_content
    @content = Content.find(params[:content_id])
  end

  def load_content_layout
    @content_layout = ContentLayout.find(params[:id])
  end

  def collect_endpoints
    @endpoints = Endpoint.all || []
  end

  def collect_layouts
    @layouts = Layout.all || []
  end
end

app/views/content_layouts/_content_layout.html.erb
<tr>
  <td class="published">
  	<div class="list-item-status <%= if content_layout.published then "approved" else "review" end%>"></div>
  </td>
  <td><%= link_to content_layout.name, [@content, content_layout] %></td>
  <td><%= content_layout.layout.type.andand.gsub("Layout", "").andand.upcase %></td>
  <td><%= time_ago_in_words(content_layout.updated_at) %> ago</td>
  <td>
    <% if current_user.role == 'admin' %>
      <% case content_layout.layout.type %>
      <% when "HtmlLayout" %>
        <%= link_to "publish", "#publishModal", data: { id: content_layout.id,
                                                        name: content_layout.name,
                                                        toggle: "modal" } %>
      <% else %>
        <%= link_to "publish", content_layouts_publish_path(content_layout) %>
      <% end %>
  	<% end %>
  </td>
  <td>
  	<%= link_to "edit", edit_content_content_layout_path(@content, content_layout) %>
  </td>
  <td>
  	<%= link_to "delete", [@content, content_layout], method: :delete, data: { confirm: "You sure?" } %>
  </td>
</tr>

app/views/content_layouts/_content_layout_endpoint_fields.erb
<div class="fields">
  <%= f.hidden_field :content_layout_id, :value => @content_layout.id %>
  <div class="form-item horizontal-item">
    <%= f.select(:endpoint_id, Endpoint.all.map{|e| ["#{e.name} (#{e.type.gsub("Endpoint", "").upcase})", e.id]}) %>
    <span class="remove-endpoint-link"><%= link_to_remove_fields( "remove", f, class: "btn") %></span>
  </div>
  <div class="clear"></div>
</div>

app/views/content_layouts/edit.html.erb
<% provide(:title, "Edit Content Layout") %>

<%= javascript_include_tag 'content_layout.js'%>

<h1><%= (@content.path + "/" + @content.name).html_safe %></h1>

<%= form_for [@content, @content_layout], :html => { :multipart => true } do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <fieldset>
    <% case @content_layout.layout.type %>
    <% when "HtmlLayout" %>
      <%= f.label :filename %>
      <%= f.text_field :name %>

      <% if @fields.empty? %>
        <p><strong>We didn't find any content tags in your layout. Did you mean to do that?</strong></p>
        <p>If you want to add content to this page insert a content tag in a layout like so,</p>
        <pre>&lt;content type="text"&gt;My Content Name&lt;/content&gt;</pre>
      <% end %>
      <% @fields.each do |key| %>
        <% if key[0] == "text" %>
          <%= f.label key[1] %>
          <%= f.text_area(:data, { id: 'editor1',
                                   class: 'ckeditor',
                                   name: "content_layout[data][#{key[1]}]",
                                   value: @data["#{key[1]}"] || "",
                                   rows: 5 }) %>
        <% elsif key[0] == "image" %>
          <% img_exists = @content_layout.images.select {|img| img.content_tag_name == key[1]}[0] %>
          <% if img_exists %>
            <%= image_tag(img_exists.source.url) %><br />
            <%= link_to "delete", img_exists, :method => :delete, :confirm => "Are you sure?"%><br />
          <% else %>
            <%= f.label key[1] %>
            <%= file_field_tag "content_layout[source][#{key[1]}]" %>
          <% end %>
        <% end %>
      <% end %>
    <% when "FacebookLayout", "TwitterLayout" %>
      <% @fields.each do |key| %>
        <div class="form-item horizontal-item">
          <%= f.label key[1] %>
          <%= f.text_field(:data, { name: "content_layout[data][#{key[1]}]",
                            value: @data["#{key[1]}"] || "" }) %>
        </div>    
      <% end %>
    <% end %>

    <div class="form-item select-endpoints">
      <label>Select Endpoints</label>
      <%= f.fields_for :content_layout_endpoints do |builder| %>
        <%= render("content_layout_endpoint_fields", :f => builder) %>
      <% end %>
      <%= link_to_add_fields("Add Endpoint", f, :content_layout_endpoints, class: "btn") %>
    </div>
    <div class="form-actions">
      <%= link_to "Back", edit_content_path(@content), class: "btn" %>
      <%= f.submit "Save", class: "btn" %>
    </div>
  </fieldset>
<% end %>
<!-- Comments -->
<div class="comments">
	<label>Comments</label>
	<ul class="comments-content">
		<%= render :partial => '/comments/comment', :collection => @content_layout.comments %>
	</ul>
	<%= form_tag "", :id => "new_comment_form" do %>
		<label>Leave Comment</label>
		<%= hidden_field_tag "comment[commentable_id]", "#{@content_layout.id}" %>
		<%= hidden_field_tag "comment[commentable_type]", "ContentLayout" %>
		<%= hidden_field_tag "comment[user_id]", "#{current_user.id}" %>
		<%= text_area_tag "comment[content]" %>
		<input class="btn right submit-comments-btn" type="submit" />
	<% end %>
</div>
<!-- Comments End -->

app/views/content_layouts/new.html.erb
<% provide(:title, 'New Content Layout') %>
<script src="/plugins/ckeditor/ckeditor.js"></script>

<h1 id="page-title">New Content Layout</h1>

<%= semantic_form_for @content_layout, url: content_content_layouts_path(@content) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <%= f.inputs do %>
    <div class="form-item horizontal-item">
  	  <%= f.input :name %>
      <%= f.input :layout_id, as: :select,
                              collection: @layouts.collect { |p| [p.name, p.id] } %>
    </div>
  <% end %>

  <div class="form-item horizontal-item">
    <label></label>
	<%= f.submit 'Create Layout', class: 'btn btn-primary' %>
  </div>
<% end %>
