config/routes.rb
Brighter::Application.routes.draw do

  root :to => 'contents#index'

  devise_for :users
  
  resources :users do
    resources :comments
  end
  resources :comments

  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  resources :folders, only: [:create, :update, :destroy]
  resources :contents, only: [:index, :edit, :new, :create, :destroy, :update] do
    get 'publish'
    resources :content_layouts, only: [:show, :new, :create, :destroy, :update, :edit]
  end
  post "content_layouts/publish" => "content_layouts#publish"
  resources :authentications, only: [:new, :create, :destroy, :index]
  resources :layouts, only: [:index, :new, :create, :destroy, :update, :edit]

  post "endpoints/register_social_app" => "endpoints#register_social_app"
  resources :endpoints, only: [:index, :new, :create, :destroy, :update, :edit]
  resources :ftp_endpoints, :controller => "endpoints", :type => "FtpEndpoint"
  resources :sftp_endpoints, :controller => "endpoints", :type => "SftpEndpoint"
  resources :html_layouts, :controller => "layouts", :type => "HtmlLayout"


  resources :facebook_endpoints,
            controller: 'endpoints',
            type: 'FacebookEndpoint',
            only: [:index, :new, :create, :destroy, :update, :edit]
  resources :twitter_endpoints,
            controller: 'endpoints',
            type: 'TwitterEndpoint',
            only: [:index, :new, :create, :destroy, :update, :edit]

  namespace :admin do
    resources :users do
      get 'lookup'
      put 'update_user'
      post 'update_user'
      post 'remove_user'
    end
  end
  resources :images

  match '/auth/:provider/callback' => 'authentications#create'
end

app/models/content.rb
class Content < ActiveRecord::Base
  attr_accessible :name, :folder, :needs_review
  attr_protected :published

  belongs_to :folder
  belongs_to :user
  has_many :content_layouts, dependent: :destroy
  has_many :comments, :as => :commentable

  validates :user, presence: true
  validates :name, presence: true, allow_blank: false

  after_update :send_notification_emails

  def publish
    content_layouts.each do |c|
      c.publish
    end
  end
  def publishable?
    content_layouts.each do |c|
      return false if not c.publishable?
    end
    return true
  end
  def send_notification_emails
    @admins = User.where(:role => "admin")
    @admins.each do |admin|
      ContentNotificationsMailer.content_reviewable(admin.email, self.id).deliver if (self.needs_review && self.needs_review_changed?)
    end
  end

  def path
    path = ""
    folder = self.folder
    while folder.parent != nil do
      path = "/" + folder.name + path
      folder = folder.parent
    end
    path
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  respond_to :html, :xml, :json

  def index
    folder_id = params[:folder_id] || 1
    @folder = Folder.find(folder_id)
    @contents = Content.accessible_by( current_ability )
    respond_with(@contents)
  end

  def content_status_filter
    if params[:filter] == 1
      @contents = Content.where( :needs_review => 1 )
    elsif params[:filter] == 2
      @contents = Content.where( :published => 1 )
    else
      @contents = Content.all
    end

    render :partial => 'content'
  end

  def create
    @content = current_user.contents.build( params[:content] )
    if @content.save
      flash[:success] = "Content created."
    end
    respond_with(@content, :location => edit_content_path(@content))
  end

  def edit
    @content = Content.find( params[:id] )
    respond_with(@content)
  end

  def new
    @content = Content.new
    respond_with(@content)
  end

  def update
    @content = Content.find( params[:id] )

    if @content.update_attributes( params[:content] )
      flash[:success] = "Content updated."
    end
    respond_with(@content, :location => edit_content_path(@content))
  end

  def destroy
    Content.find( params[:id] ).destroy
    flash[:success] = "Content deleted."
    respond_with(@content)
  end

  def publish
    @content = Content.find( params[:content_id] )

    successes = []
    failures = []
    @content.content_layouts.each do |b|
      if !b.published? and b.publish
        successes << b.name
      else
        failures << b.name
      end
    end
    if failures.empty?
      flash[:success] = "Content published successfully."
    else
      flash[:success] = "#{successes.join(", ")} published."
      flash[:error] = "#{failures.join(", ")} could not be published."
    end
    ContentNotificationsMailer.content_published(@content).deliver
    @content.update_attributes(needs_review:false)
    respond_with(@content) do |format|
      format.html { redirect_to contents_url }
      format.xml { render @content.to_xml }
      format.json { render @content.to_json }
    end
  end

end

app/helpers/content_helper.rb
module ContentHelper
end

app/views/contents/_content.html.erb
  <tr class="the-list">
    <td class="published">
    	<%
		    fully_published = true

		    content.content_layouts.each do |b|
		      fully_published = false if b.published == false || b.published.nil?
		    end
    	%>
    	<div class="list-item-status <%= if fully_published && !content.needs_review then "approved" else "review" end%>"></div>
    </td>
    <td class="title"><%= link_to content.name, edit_content_path(content) %></td>
    <td class="author"><%= content.user.email %></td>
    <td class="date"><%= time_ago_in_words(content.updated_at) %> ago</td>
    <td class="action">
      <% if (!fully_published || content.needs_review) &&  current_user.role == 'admin' %>
      	<%= link_to "publish", "/contents/" + content.id.to_s + "/publish", class: "action-link" %> &nbsp;
      <% end %>
      <%= link_to "edit", edit_content_path(content), class: "action-link" %> &nbsp;
      <%= link_to "delete", content, method: :delete, data: { confirm: "You sure?" }, class: "action-link" %>
    </td>
  </tr>

app/views/contents/_list_content.html.erb
<div>
  <select class="pull-right content_status">
    <option value="0">ALL</option>
    <option value="1">Needs Review</option>
    <option value="2">Published</option>
  </select>
</div>

<div class="clear"</div>

<table class="content-list">
  <tr class="heading">
    <td class="status">Status</td>
    <td class="title">Content Title</td>
    <td class="author">Author</td>
    <td class="date">Last Modified</td>
    <td class="action">Action</td>
  </tr>
    <%= render @contents %>
</table>

app/views/contents/edit.html.erb
<% provide(:title, 'Edit Content') %>
<%= javascript_include_tag 'content.js' %>
<h1>Edit Content</h1>

<h2 id="content_path" data-path="<%= @content.path %>"><%= (@content.path + "/" + @content.name).html_safe %></h2>

<%= form_for @content, html: { class: "form-inline" } do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.text_field :name %>

  <%= f.button "Update Title", class: "btn" %>
<% end %>

<table class="table table-condensed table-hover">
  <thead>
    <tr>
      <th>Status</th>
      <th>Name</th>
      <th>Category</th>
      <th>Last modified</th>
    </tr>
  </thead>
  <tbody>
    <%= render @content.content_layouts %>
  </tbody>
</table>

<%= link_to "Add Layout", new_content_content_layout_path(@content),
                        class: "btn btn-large",
                        style: "float:left; margin-right:10px" %>
<% if @content.needs_review %>
  <div class="btn btn-large disabled">Review in Progress</div>
<% else %>
  <%= form_for @content, html: { class: 'form-inline' } do |f| %>
    <%= f.hidden_field :needs_review, :value => 1 %>
    <%= f.submit "Mark For Review", class: "btn btn-large" %>
  <% end %>
<% end %>

<!-- Comments -->
<div class="comments">
	<label>Comments</label>
	<ul class="comments-content">
		<%= render :partial => '/comments/comment', :collection => @content.comments %>
	</ul>
	<%= form_tag "", :id => "new_comment_form" do %>
		<label>Leave Comment</label>
		<%= hidden_field_tag "comment[commentable_id]", "#{@content.id}" %>
		<%= hidden_field_tag "comment[commentable_type]", "Content" %>
		<%= hidden_field_tag "comment[user_id]", "#{current_user.id}" %>
		<%= text_area_tag "comment[content]" %>
		<input class="btn right submit-comments-btn" type="submit" />
	<% end %>
</div>
<!-- Comments End -->

<!-- Modal -->
<div id="publishModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="publishModalLabel" aria-hidden="true">
  <%= form_for "", url: "/content_layouts/publish", html: { id: "publish_form" } do %>
    <div><%= hidden_field_tag "id" %></div>
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 id="publishModalLabel">Publish content layout</h3>
    </div>
    <div class="modal-body">
      <p>Publish to this path on the servers?</p>
      <%= text_field_tag "path", @content.path %>
      <p>with this file name?</p>
      <%= text_field_tag "filename" %>
    </div>
    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      <button type="submit" class="btn btn-primary">Publish</button>
    </div>
  <% end %>
</div>

<script>
  $(document).ready(function() {
    $('a[data-toggle="modal"]').each(function(_, el) {
      $(el).click(function() {
        $('#publish_form #id').val($(el).data('id'));
        $('#publish_form #filename').val($(el).data('name'));
        $('#publish_form #path').val($('#content_path').data('path'));
      });
    });
  });

</script>

app/views/contents/index.html.erb
<% provide(:title, 'Content Management') %>
<h1 id="page-title">Content Management</h1>

<ul id="viewTabs" class="nav nav-tabs">
  <li><a href="#folder" data-toggle="tab">Folder View</a></li>
  <li><a href="#list" data-toggle="tab">List View</a></li>
</ul>
<div id="viewTabsContent" class="tab-content">
  <div class="tab-pane" id="folder">
    <%= render @folder %>
  </div>
  <div class="tab-pane" id="list">
    <%= render 'list_content' %>
  </div>
</div>

<script>
$('#viewTabs a').click(function (e) {
  e.preventDefault()
  $(this).tab('show')
})
$(document).ready(function() {
  $('#viewTabs li:eq(0) a').tab('show')
})
</script>

app/views/contents/new.html.erb
<% provide(:title, "Create New Content") %>
<h1>Create Content</h1>

<%= form_for @content do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit 'Create Content', class: "button add-new-content submit right" %>
<% end %>