config/routes.rb
Brighter::Application.routes.draw do

  root :to => 'contents#index'

  devise_for :users
  
  resources :users do
    resources :comments
  end
  resources :comments

  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  resources :folders, only: [:create, :update, :destroy]
  resources :contents, only: [:index, :edit, :new, :create, :destroy, :update] do
    get 'publish'
    resources :content_layouts, only: [:show, :new, :create, :destroy, :update, :edit]
  end
  post "content_layouts/publish" => "content_layouts#publish"
  resources :authentications, only: [:new, :create, :destroy, :index]
  resources :layouts, only: [:index, :new, :create, :destroy, :update, :edit]

  post "endpoints/register_social_app" => "endpoints#register_social_app"
  resources :endpoints, only: [:index, :new, :create, :destroy, :update, :edit]
  resources :ftp_endpoints, :controller => "endpoints", :type => "FtpEndpoint"
  resources :sftp_endpoints, :controller => "endpoints", :type => "SftpEndpoint"
  resources :html_layouts, :controller => "layouts", :type => "HtmlLayout"


  resources :facebook_endpoints,
            controller: 'endpoints',
            type: 'FacebookEndpoint',
            only: [:index, :new, :create, :destroy, :update, :edit]
  resources :twitter_endpoints,
            controller: 'endpoints',
            type: 'TwitterEndpoint',
            only: [:index, :new, :create, :destroy, :update, :edit]

  namespace :admin do
    resources :users do
      get 'lookup'
      put 'update_user'
      post 'update_user'
      post 'remove_user'
    end
  end
  resources :images

  match '/auth/:provider/callback' => 'authentications#create'
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  attr_accessible :name, :folder_id
  has_many :folders
  belongs_to :parent, class_name: 'Folder', foreign_key: 'folder_id'
  has_many :content

  def path
    path = ""
    folder = self
    while folder.parent != nil do
      path = "/" + folder.name + path
      folder = folder.parent
    end
    path
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_filter :authenticate_user!

  def create
    folder = Folder.find(params[:folder][:folder_id])
    folder.folders.build(params[:folder])
    if folder.save
      flash[:success] = "Folder created successfully."
      redirect_to contents_path(folder_id: folder.id)
    else
      flash[:error] = folder.errors.full_message
      redirect_to contents_path(folder_id: folder.id)
    end
  end

  def update
    folder = Folder.find(params[:id])
    if folder.update_attributes(params[:folder])
      flash[:success] = "Folder updated successfully."
      redirect_to contents_path
    else
      flash[:success] = folder.errors.full_messages.inspect
      redirect_to contents_path
    end
  end
end

app/views/folders/_folder.html.erb
<h2><%= @folder.path %></h2>
<ul class="jqueryFileTree">
  <% @folder.folders.each do |nested_folder| %>
  <li class="directory collapsed">
    <%= link_to nested_folder.name,
                contents_path(folder_id: nested_folder.id),
                data: { type: "folder",
                        id: nested_folder.id } %>
  </li>
  <% end %>
  <% @folder.content.accessible_by(current_ability).each do |content| %>
  <li class="file ext_html">
    <%= link_to content.name, edit_content_path(content) %>
  </li>
  <% end %>
</ul>

<div class="btn-toolbar well well-small">

  <div class="btn-group">
    <a href="#newContentModal" role="button" class="btn" data-toggle="modal">
      <i class="icon-plus-sign"></i>Add New Content
    </a>
  </div>

  <div class="btn-group">
    <%= link_to(contents_path(folder_id: @folder.folder_id),
                               class: 'btn')  do %>
                               <i class='icon-arrow-up'></i>Up a folder
    <% end %>

    <a href="#newFolderModal" role="button" class="btn" data-toggle="modal">
      <i class="icon-plus"></i>Add New Folder
    </a>
  </div>
</div>

<div id="newFolderModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="newFolderModal" aria-hidden="true">
  <%= form_for @folder.folders.build(folder_id: @folder.id) do |f| %>
  <div><%= f.hidden_field :folder_id %></div>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="newFolderModal">Add New Folder</h3>
  </div>
  <div class="modal-body">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <%= f.submit "Save changes", class: "btn btn-primary" %>
  </div>
  <% end %>
</div>

<div id="newContentModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="newContentModal" aria-hidden="true">
  <%= form_for @folder.content.build(folder_id: @folder.id) do |f| %>
  <div><%= f.hidden_field :folder_id %></div>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="newContentModal">Add New Content</h3>
  </div>
  <div class="modal-body">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <%= f.submit "Save changes", class: "btn btn-primary" %>
  </div>
  <% end %>
</div>