config/routes.rb
Brighter::Application.routes.draw do

  root :to => 'contents#index'

  devise_for :users
  
  resources :users do
    resources :comments
  end
  resources :comments

  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  resources :folders, only: [:create, :update, :destroy]
  resources :contents, only: [:index, :edit, :new, :create, :destroy, :update] do
    get 'publish'
    resources :content_layouts, only: [:show, :new, :create, :destroy, :update, :edit]
  end
  post "content_layouts/publish" => "content_layouts#publish"
  resources :authentications, only: [:new, :create, :destroy, :index]
  resources :layouts, only: [:index, :new, :create, :destroy, :update, :edit]

  post "endpoints/register_social_app" => "endpoints#register_social_app"
  resources :endpoints, only: [:index, :new, :create, :destroy, :update, :edit]
  resources :ftp_endpoints, :controller => "endpoints", :type => "FtpEndpoint"
  resources :sftp_endpoints, :controller => "endpoints", :type => "SftpEndpoint"
  resources :html_layouts, :controller => "layouts", :type => "HtmlLayout"


  resources :facebook_endpoints,
            controller: 'endpoints',
            type: 'FacebookEndpoint',
            only: [:index, :new, :create, :destroy, :update, :edit]
  resources :twitter_endpoints,
            controller: 'endpoints',
            type: 'TwitterEndpoint',
            only: [:index, :new, :create, :destroy, :update, :edit]

  namespace :admin do
    resources :users do
      get 'lookup'
      put 'update_user'
      post 'update_user'
      post 'remove_user'
    end
  end
  resources :images

  match '/auth/:provider/callback' => 'authentications#create'
end

app/models/layout.rb
class Layout < ActiveRecord::Base
  attr_accessible :name, :content, :type

  validates :name, presence: true
  validates :type, presence: true

  has_many :content_layouts

  has_paper_trail

  def get_fields
    read_attribute(:content).scan(/<content type=\"(image|text)\">([\w|\s]*?)<\/content>/)
  end

  # def endpoints
  #   raise "NOT IMPLEMENTED"
  # end

  def combine data
    raise "NOT IMPLEMENTED"
  end
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html, :xml, :json

  def index
    @layouts = Layout.where(type: "HtmlLayout")
    respond_with(@layouts)
  end

  def create
    @layout = Layout.new(params[:layout])
    if @layout.save
      flash[:success] = "Layout created."
      respond_with(@layout, :location => edit_layout_path(@layout))
    end
  end

  def new
    @layout = Layout.new
    respond_with(@layout)
  end

  def edit
    @layout = Layout.find(params[:id])
    respond_with(@layout)
  end

  def update
    puts params
    @layout = Layout.find(params[:id])
    if @layout.update_attributes(params[:layout])
      flash[:success] = "Layout updated. #{undo_link}"
    end
    respond_with(@layout, :location => edit_layout_url)
  end

  def destroy
    Layout.find(params[:id]).destroy
    flash[:success] = "Layout destroyed."
    respond_with(@layout)
  end

  private 

  def undo_link
    view_context.link_to("undo", revert_version_url(@layout.versions.scoped.last), :method => :post)
  end
end

app/views/layouts/_account_menu.html.erb
<div class="account-menu right">
	<ul>
		<li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %>, <%= current_user.display_name %></li>
	</ul>
</div>

app/views/layouts/_fields.html.erb

<%= f.hidden_field :type, value: "HtmlLayout" %>

<div class="form-item">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="form-item">
  <%= f.label :content %>
  <%= f.text_area :content, :id => 'code_editor' %>
</div>

<%= render 'shared/html_editor' %>


app/views/layouts/_header.html.erb
 <header>
  <div class="inner navbar">
    <%= link_to image_tag('/images/cms-logo.png'), root_path, class: 'main-logo' %>
    <% if user_signed_in? %>
      <div class="admin-status">
        <%= render 'layouts/account_menu' %>
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/_layout.html.erb
<tr>
  <td><%= layout.name %></td>
  <td><%= time_ago_in_words(layout.updated_at) %> ago</td>
  <td><%= link_to "edit", edit_layout_path(layout) %></td>
  <td><%= link_to "delete", layout, method: :delete,
                                    data: { confirm: "You sure?" } %></td>
</tr>

app/views/layouts/_left_side_bar.html.erb
 <ul>
  <li>
    <%= link_to "Content", contents_path %>
  </li>
  <li>
    <%= link_to "Endpoints", endpoints_path %>
  </li>
  <li>
    <%= link_to "Layouts", layouts_path %>
  </li>
  <li>
    <%= link_to 'User Accounts', admin_users_path %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  	<title><%= full_title(yield(:title)) %></title>
      <link href="/stylesheets/css-reset.css"   media="all" rel="stylesheet" type="text/css" />
	  	<%= stylesheet_link_tag    "application",  :media => "all" %>
      <link href="/stylesheets/fonts.css"     media="all" rel="stylesheet" type="text/css" />
      <link href="/stylesheets/global.css"    media="all" rel="stylesheet" type="text/css" />

  		<%= javascript_include_tag "application" %>
  		<script src="/javascripts/ckeditor.js" type="text/javascript" ></script>
  		<script src="/javascripts/global.js" type="text/javascript"></script>
  		<script src="/javascripts/plugins/autosize-master/jquery.autosize.js" type="text/javascript"></script>

	  	<%= csrf_meta_tags %>
	</head>
	<body>
    <!-- Begin Header -->
    <header>
      <div class="inner">
        <img src="/images/cms-logo.png" class="main-logo">
        <div class="admin-status">  
          <%= render 'layouts/account_menu' if user_signed_in? %>
        </div>
      </div>
    </header>
    <!-- End Header -->
    <!-- Begin Main Content -->
    <div class="main-content">
      <% if user_signed_in? %>
        <!-- Begin Left Nav -->
        <nav>
          <%= render 'layouts/left_side_bar' %>
        </nav>
        <!-- End Left Nav -->

        <!-- Begin Page Content -->
        <div class="content">
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value.html_safe, class: "alert alert-#{key}") %>
          <% end %>
          <%= yield %>

      <% else %>
        <%= yield %>
      <% end %>

          <div class="debug-message">
            <%= debug(params) if Rails.env.development? %>
          </div>
      </div>
      <!-- End Page Content -->
      <div class="clear"></div>
    </div>
    <!-- End Main Content -->
  </body>
</html>

app/views/layouts/edit.html.erb
<% provide(:title, 'Edit Layout') %>
<h1 id="page-title">Edit Layout</h1>
<div class="breadcrumbs">
</div>

<%= form_for @layout, :as => :layout do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <%= render 'fields', f: f %>

  <%= link_to "Back", layouts_path, class: "btn" %>
  <%= f.button "Save", class: "btn" %>
<% end %>

app/views/layouts/index.html.erb
<% provide(:title, "Layouts") %>
<h1 id="page-title">Layouts</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Last Modified</th>
    </tr>
  </thead>
  <tbody>
    <% @layouts.each do |lay| %>
      <%= render partial: "layouts/layout", locals:{layout: lay} %>
    <% end %>
  </tbody>
</table>
<%= link_to "Add Layout", new_layout_path, class: "btn" %>

app/views/layouts/new.html.erb
<% provide(:title, 'New Layout') %>

<h1 id="page-title">New Layout</h1>
<div class="breadcrumbs">
</div>

<%= form_for @layout do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= render 'fields', f: f %>

  <%= f.submit "Create Layout", :class => "btn" %>

<% end %>